import React, { useEffect } from 'react'
import { Table, Card, CardBody } from 'reactstrap';
import { useState, useContext } from 'react';
import { AuthContext } from 'contexts/app/AuthContext';
import { axiosInstance } from 'contexts/app/Generalvariables';
import { DeviceRow } from 'components/app/Views/DeviceRow';




// Generated by https://quicktype.io

export interface Response {
    _id:        string;
    userId:     string;
    deviceId:   string;
    deviceName: string;
    username:   string;
    password:   string;
    subscribe:  string;
    publish:    string;
    __v:        number;
}


export const Devices = () => {

    const [rows, setRows] = useState<Response[]>([])
    const {authContextState} = useContext(AuthContext)


    
    useEffect(() => {
        const fillRows = async () => {
            try{
    
                const {data} = await axiosInstance.get<Response[]>('/api/getDevices', {
                    params : {
                        userId : authContextState.userId
                    }
                })
    
                console.log(data);
    
                setRows(data)
    
            }catch(e){  
                
            }
    
    
        }
        fillRows()
        
    }, [authContextState.userId])

    return (
        <div className="content" style={{overflow : 'hidden'}}>
            <Card>
                <CardBody>

                    <Table responsive>
                        <thead>
                            <tr>
                                <th>DeviceId</th>
                                <th>DeviceName</th>
                                <th className="">Username</th>
                                <th className="">Password</th>
                                <th className="">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {
                                rows.map(value => {
                                    return (
                                        <DeviceRow 
                                            deviceId = {value.deviceId}
                                            deviceName = {value.deviceName}
                                            password = {value.password}
                                            username = {value.username}
                                            key = {value.deviceId}
                                        />
                                    )
                                })
                            }
    
                        </tbody>
                    </Table>


                </CardBody>
            </Card>
        </div>
    )
}
