import { Table, Card, CardBody, CardText, Row, Button } from 'reactstrap';
import { DeviceRow } from 'components/app/Views/DeviceRow';
import { InputField } from 'components/app/Forms/InputField';
import { BackgroundColorContext, classMappingColors } from 'contexts/core/BackgroundColorContext';
import { useDevices } from '../../hooks/views/useDevices';




// Generated by https://quicktype.io



export const Devices = () => {
    const {clickHandler, handleSubmit, register, rows, sizeOfInputs} = useDevices()


    return (
        <div className="content" style={{overflow : 'hidden'}}>
            <Card>
                <CardBody>
                    <CardText>Create a device</CardText>
                    <Row>
                        <InputField 
                            label = "DeviceId"
                            placeholder = "Device ID"
                            size = {sizeOfInputs}
                            type = "text" 
                            register = {register("deviceId")}
                        />
                        <InputField 
                            label = "DeviceName"
                            placeholder = "DeviceName"
                            size = {sizeOfInputs}
                            type = "text" 
                            register = {register("deviceName")}
                        />
                        <InputField 
                            label = "Username"
                            placeholder = "Username"
                            size = {sizeOfInputs}
                            type = "text" 
                            register = {register("username")}
                        />
                        <InputField 
                            label = "Password"
                            placeholder = "Password"
                            size = {sizeOfInputs}
                            type = "text" 
                            register = {register("password")}
                        />
                    </Row>
                    
                    <BackgroundColorContext.Consumer>
                    {({color}) => ( 
                        <Button type='button' color={classMappingColors[color]} onClick = {handleSubmit(clickHandler)}>Save</Button>
                    )}
                    </BackgroundColorContext.Consumer>
                    

                </CardBody>
            </Card>
            <Card>
                <CardBody>

                    <Table responsive>
                        <thead>
                            <tr>
                                <th>DeviceId</th>
                                <th>DeviceName</th>
                                <th className="">Username</th>
                                <th className="">Password</th>
                                <th className="">Actions</th>
                            </tr>
                            {
                                rows.map(value => {
                                    return (
                                        <DeviceRow 
                                            deviceId = {value.deviceId}
                                            deviceName = {value.deviceName}
                                            password = {value.password}
                                            username = {value.username}
                                            key = {value.deviceId}
                                        />
                                    )
                                })
                            }


                        </thead>
                        <tbody>
    
                        </tbody>
                    </Table>


                </CardBody>
            </Card>
        </div>
    )
}
